### ISSUE TITLE
cudaSafeCall() Runtime API error : out of memory.

### ISSUE THREAD

**Issue by xxsong5** [martinruenz/co-fusion#1]
xxsong5@xxsong5:~/co-fusion/build/GUI$ ./CoFusion  -l /media/xxsong5/SAMSUNG/data_real_intel/outintel.klg
Reading log file: /media/xxsong5/SAMSUNG/data_real_intel/outintel.klg which has 3861 frames. 
Initialised MainController. Frame resolution is set to: 640x480
Exporting results to: /media/xxsong5/SAMSUNG/data_real_intel/outintel.klg-export//
Created model with max number of vertices: 9437184
Initialised Multi-Object Fusion. Each model can have up to 9437184 surfel (TEXTURE_DIMENSION: 3072x3072).
New label detected (40,184 72,376) - try relocating...
Found new model.
Created model with max number of vertices: 9437184
Lost a model.
Deactivating model... keeping data. Surfels: 12935 confidence threshold: 0.496591
New label detected (40,24 88,136) - try relocating...
Found new model.
/home/xxsong5/co-fusion/Core/Cuda/containers/device_memory.cpp(203) : cudaSafeCall() Runtime API error : out of memory.
/home/xxsong5/co-fusion/Core/GPUTexture.cpp(79) : cudaSafeCall() Runtime API error : out of memory.

**Comment by martinruenz** [comment]
This error is due to the GPU running out of memory. Try setting the `COFUSION_NUM_SURFELS`, as described in the readme. Also make sure that memory is freed after losing a model (Don't set `-keep` option, also check GUI). The last option would be to get a GPU with more memory.

**Comment by wolf943134497** [comment]
hi, @xxsong5 . Did you run successfully? 
can you peovide the environment configuration and  Dependencies version ? thanks !
After building co-fusion, how to test by using own image? Thanks!

**Comment by xxsong5** [comment]
yes, @wolf943134497 finally it worked by changing ```CONFUSION_NUM_SURFELS```. If you want to run it on your own images,  you can convert your datas to ```.klg``` file, then run this program by using ``` -l``` option. 
 By the way, I provide a tool at  https://github.com/xxsong5/image_to_klg  to convert images to ```.klg``` file.

**Comment by wolf943134497** [comment]
Hi,  @xxsong5  Thanks for your suggestions and sharing.
Can you provide a detailed steps? And the  environment configuration and Dependencies version that you use.Thanks!
