### ISSUE TITLE
build error on Co-Fusion part

### ISSUE THREAD

**Issue by YanhaoZhang** [martinruenz/co-fusion#12]
Hi 
I followed the install.sh file to build co-fusion. However on the final part, when running make -j8, I met this error:
![image](https://user-images.githubusercontent.com/36495922/46283625-3940c300-c5b8-11e8-893a-707bd72e699e.png)

May I ask you some advice on that? I am using ubuntu14, the cuda version is 8.0. For other packages, I just follow install.sh file. Many thanks.

Cheers,
Yanhao

**Comment by mylxiaoyi** [comment]
maybe you need to update pangolin to the newest version.

**Comment by zss1995** [comment]
> Hi
> I followed the install.sh file to build co-fusion. However on the final part, when running make -j8, I met this error:
> ![image](https://user-images.githubusercontent.com/36495922/46283625-3940c300-c5b8-11e8-893a-707bd72e699e.png)
> 
> May I ask you some advice on that? I am using ubuntu14, the cuda version is 8.0. For other packages, I just follow install.sh file. Many thanks.
> 
> Cheers,
> Yanhao

Hello, I have met the same question as you, have you solved it, could you please give some advice?

**Comment by martinruenz** [comment]
`frustrum` was renamed to `frustum` in *Pangolin* as there was a typo. Your Co-Fusion / Pangolin versions seem to be out of sync. Are you using the latest for both?

I'll close this issue now, assuming that it is fixed by updating the codebase. But please let me know in case the issue persists!
