### ISSUE TITLE
what's mean of  Your GPU "GeForce GT 740M" isn't in the ICP Step performance database

### ISSUE THREAD

**Issue by CNchence** [martinruenz/co-fusion#3]
when i run ./CoFusion -l  /to/my/teddy-handover.klg , and i get that   
Your GPU "GeForce GT 740M" isn't in the ICP Step performance database, please add it
Your GPU "GeForce GT 740M" isn't in the RGB Step performance database, please add it
Your GPU "GeForce GT 740M" isn't in the RGB Res performance database, please add it
Your GPU "GeForce GT 740M" isn't in the SO3 Step performance database, please add it
what does that mean?

**Comment by martinruenz** [comment]
Is is possible to specify the number of threads and blocks used based on your GPU. Have a look at this file to see how this is done:
https://github.com/martinruenz/co-fusion/blob/master/Core/Utils/GPUConfig.h
