### ISSUE TITLE
CoFusion crashes when exit

### ISSUE THREAD

**Issue by BruceCanovas** [martinruenz/co-fusion#4]
Hi,

I managed to build CoFusion on Xenial with Cuda9 (I have an Nividia Geforce GTX950 M). Everything seems to work but very often, when I quit the program by shutting off the window or with Ctrl-c my screen freezes and I have to force shutdown with the power button... Has anyone observed the same behavior, or get an idea about what is going wrong?

Thank you.

**Comment by martinruenz** [comment]
Hi Bruce,

I didn't notice this behaviour yet -- it might be Cuda9 related. Could you run a debug build and add some breakpoints to important destructors (Model, CoFusion, ...). This might give some insights about the crashes. Further, running with valgrind and parameters `--db-attach=yes --log-file=<filename> --leak-check=full` or `--vgdb-error=0 --log-file=<filename> --leak-check=full` could give valuable information.
Which data are you feeding to the program? (Live data, a klg file, image data)

**Comment by BruceCanovas** [comment]
Well you may be right about Cuda9, I tried on my other laptop's partition with ubuntu trusty and cuda 7.5 and did not face the crash ... I use both live and klg data.

**Comment by BruceCanovas** [comment]
Finally there is probably something wrong with my system setup because on an other machine with Cuda9 and Xenial everything is right too (only the GPU differs as the first one was 950GTX M and the second 960 GTX M) ... I think we can close the issue as it doesn't seems to be related with your code.

**Comment by martinruenz** [comment]
Okay, let me know if I should re-open the issue.
