### ISSUE TITLE
Frame and intrinsics

### ISSUE THREAD

**Issue by BruceCanovas** [martinruenz/co-fusion#6]
Hi (sorry for this third post),

As I want to use your work with different cameras I wanted to know at which sensor (rgb or depth?) correspond exactly the intrinsic parameters? Moreover I wanted to be sure that rgb and depth frames should be provided already rectified and registered.

Thank you

**Comment by martinruenz** [comment]
Hi Bruce,
your assumption is right: the data is assumed to be registered and the parameters correspond to the resulting model. Frameworks, such as OpenNI, can help you with this process. If you do registration manually, you should also know the parameters for the resulting model.

It might be useful to have a look at the different log-readers, see:
https://github.com/martinruenz/co-fusion/tree/master/GUI/Tools
