### ISSUE TITLE
Co-fusion build exception

### ISSUE THREAD

**Issue by MINDoSOFT** [martinruenz/co-fusion#7]
Hello everyone.

I am getting an error when I am trying to run : 
`python3 install.py -a`

The OS is Ubuntu 16.04.4 Xenial.

The only thing that I have adjusted trying to resolve the issue is in the install.py and install.sh wherever there is "make -j8", replaced with "make -j6". Because my CPU has 6 cores.

The error is the following :
`no match for ‘operator=’ (operand types are ‘std::unique_ptr<pangolin::VideoInterface>’ and ‘pangolin::VideoInterface*’)`

You can find a detailed log of the build [here](https://pastebin.com/sWSBLH22).

Any ideas why this exception is occuring?

**Comment by martinruenz** [comment]
Hi,
this is related to https://github.com/martinruenz/co-fusion/pull/2
Essentially, you have to use the master branch of pangolin, instead of the custom fork in the python install script. This is already done in the `install.sh` script. I'll update the python script when I have time (probably at the end of next week).

**Comment by MINDoSOFT** [comment]
Hello. I have done the following changes and was able to build co-fusion. Thanks for the guidance.

``` diff --git a/Scripts/install.py b/Scripts/install.py
index 5ad23e9..49b82d5 100755
--- a/Scripts/install.py
+++ b/Scripts/install.py

@@ -329,8 +329,8 @@ def installFromSource(path):
     # Pangolin
 
     cmds = [
-        ('git clone --depth=1 --branch devel '
-         'https://github.com/martinruenz/Pangolin.git'),
+        ('git clone --depth=1 --branch master '
+         'https://github.com/stevenlovegrove/Pangolin.git'),
         'mkdir -p Pangolin/build'
     ]
 
```
