### ISSUE TITLE
Question about GPU memory 

### ISSUE THREAD

**Issue by Qidian213** [martinruenz/co-fusion#8]
Hi , i  used this project to run on my  laptop computer with an Nvidia GeForce  GTX 1060 6g , but i oftern got my computer crashed with the memory of GPU only about 70M left . From the README i found "the `COFUSION_NUM_SURFELS` CMake option can help reduce the memory footprint per model" , so how can i do it ? thanks !

**Comment by martinruenz** [comment]
This option allows you to set the max number of surfels for models, you could pick a value of 0.5m, for example, and test if this fits your hardware better: `-DCOFUSION_NUM_SURFELS=500000`

**Comment by Qidian213** [comment]
Thanks , it is useful for me !
